[package]
name = "wasm-webidl-bindings-text-parser"
version = "0.1.2"
authors = ["The Rust and WebAssembly Working Group"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
failure = "0.1.5"
lalrpop-util = "0.17.1"
leb128 = "0.2.4"
regex = "1.1.7"
walrus = "0.8.0"
